name: Android Release APK Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build release APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
